"""Approach #1 (LoRA distillation) prep, step 2/2: LoRA-fine-tune a vision-
language model to reproduce the code-grounded descriptions generated by
generate_vision_distillation_dataset.py, instead of relying on its own
(sometimes wrong) spatial reasoning about an ARC-AGI-3 frame.

Base model: Qwen2.5-VL-3B-Instruct (Apache 2.0, HF-native checkpoint --
NOT the Ollama GGUF used for the plain chat comparisons earlier). Apache
2.0 chosen over Gemma specifically because this produces a NEW derived
model, and this project's open-source-weights constraint for prize
eligibility (see GUIDELINE.md) is cleaner with a fully OSI-approved base.

LoRA only touches the LANGUAGE model's attention/MLP projections -- the
vision tower and the vision-language merger stay frozen. Rationale: the
problem being fixed is spatial-RELATIONAL reasoning in language (Gemma and
Qwen2.5-VL both correctly SEE the pixels, e.g. "blob_2 and blob_3 form a
cross-like intersection" — colors/shapes are noticed, but the relationship
between them is wrong). Freezing vision preserves whatever real visual
features the base model already extracts; only the reasoning-over-those-
features head is adapted.

NOT YET RUN (explicit user request: prepare only). Sanity-check before a
real run:
    python3 train_vision_lora.py --dataset-dir <dir> --max-steps 5 --dry-run
runs a few steps on CPU/tiny batch to confirm the data pipeline and loss
computation work, without committing to a real training budget.

Usage (real run, once launched):
    python3 train_vision_lora.py --dataset-dir checkpoints/vision_distillation_dataset \
        --output-dir checkpoints/qwen25vl_lora_vision --epochs 3
"""
from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "src"))

MODEL_ID = "Qwen/Qwen2.5-VL-3B-Instruct"

SYSTEM_PROMPT = """\
You are the vision module for a game-playing agent. You are given an image \
with object id labels (blob_0, blob_1, ...) drawn on it. Describe the \
objects and how they relate to each other -- pay close attention to whether \
two same-colored objects that look close together are actually two separate \
objects or one object split by something else sitting between them.
"""


class VisionDistillationDataset:
    """Thin wrapper around the manifest.jsonl written by
    generate_vision_distillation_dataset.py -- kept as a plain class (not a
    torch.utils.data.Dataset subclass) so this file has zero heavy imports at
    module load time; the real Dataset subclass is built lazily inside
    build_dataset() once torch/PIL are actually needed (mirrors
    train_brain_grpo.py's existing pattern of deferring heavy imports)."""

    def __init__(self, dataset_dir: str):
        self.dataset_dir = dataset_dir
        manifest_path = os.path.join(dataset_dir, "manifest.jsonl")
        with open(manifest_path) as f:
            self.examples = [json.loads(line) for line in f if line.strip()]

    def __len__(self) -> int:
        return len(self.examples)

    def __getitem__(self, idx: int) -> dict:
        ex = self.examples[idx]
        return {
            "image_path": os.path.join(self.dataset_dir, ex["image_path"]),
            "target_text": ex["target_text"],
        }


def build_torch_dataset(manifest: VisionDistillationDataset, processor):
    """Builds a torch.utils.data.Dataset that yields tokenized, loss-masked
    (input_ids, labels, pixel_values, ...) tensors ready for a standard
    causal-LM training loop. Loss is masked to ONLY the target_text tokens
    (the system+user+image portion is context, not something to learn to
    generate) -- otherwise the model would partially learn to reproduce the
    prompt text itself, diluting gradient signal on the part that matters."""
    import torch
    from PIL import Image
    from torch.utils.data import Dataset

    class _TorchDataset(Dataset):
        def __len__(self):
            return len(manifest)

        def __getitem__(self, idx):
            ex = manifest[idx]
            image = Image.open(ex["image_path"]).convert("RGB")
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": "Describe this frame."}]},
            ]
            prompt_text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            full_text = prompt_text + ex["target_text"] + processor.tokenizer.eos_token

            prompt_ids = processor(text=prompt_text, images=image, return_tensors="pt")["input_ids"][0]
            full = processor(text=full_text, images=image, return_tensors="pt")

            labels = full["input_ids"][0].clone()
            labels[: len(prompt_ids)] = -100  # mask the prompt -- only the target_text contributes to loss

            # Qwen2.5-VL's processor does NOT return pixel_values as a normal
            # [batch, ...] image tensor -- it's already a packed patch sequence
            # ([total_patches, patch_dim], confirmed empirically: shape (1296, 1176)
            # for one 512x512 image, no leading batch-of-1 to strip). Blindly
            # squeezing every multi-dim tensor's first axis (the naive
            # `v[0] if v.dim()>1` this replaced) silently sliced pixel_values down
            # to ONE patch row and corrupted image_grid_thw, causing a reshape
            # crash deep in the vision tower on the first real training batch --
            # caught via --dry-run before it could waste a real training run.
            # Only input_ids/attention_mask/mm_token_type_ids are actually
            # [1, seq_len] and need the batch-of-1 dropped.
            squeeze_keys = {"input_ids", "attention_mask", "mm_token_type_ids"}
            item = {k: (v[0] if k in squeeze_keys else v) for k, v in full.items()}
            item["labels"] = labels
            return item

    return _TorchDataset()


def train(dataset_dir: str, output_dir: str, epochs: int = 3, lr: float = 1e-4,
          lora_r: int = 16, lora_alpha: int = 32, max_steps: int | None = None,
          dry_run: bool = False) -> None:
    import torch
    from peft import LoraConfig, get_peft_model
    from transformers import (
        AutoProcessor,
        Qwen2_5_VLForConditionalGeneration,
        Trainer,
        TrainingArguments,
    )

    print(f"loading {MODEL_ID}...")
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        MODEL_ID, dtype=torch.bfloat16, device_map="auto",
    )

    # LoRA on the language-model attention/MLP projections only -- vision
    # tower (model.visual.*) and the merger stay frozen, see module docstring
    lora_config = LoraConfig(
        r=lora_r, lora_alpha=lora_alpha, lora_dropout=0.05, bias="none",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    manifest = VisionDistillationDataset(dataset_dir)
    print(f"{len(manifest)} examples in dataset")
    torch_dataset = build_torch_dataset(manifest, processor)

    args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=1,  # vision-language batches are memory-heavy; grad-accumulate instead
        gradient_accumulation_steps=8,
        learning_rate=lr,
        logging_steps=5,
        save_strategy="epoch",
        max_steps=max_steps if max_steps is not None else -1,
        bf16=True,
        report_to=[],
    )

    trainer = Trainer(model=model, args=args, train_dataset=torch_dataset)

    if dry_run:
        print("dry-run: building one batch and computing loss, not training")
        batch = torch_dataset[0]
        # same distinction as build_torch_dataset's __getitem__: pixel_values/
        # image_grid_thw are already in their natural (no fake batch-of-1) shape,
        # only the text-side tensors need an added batch dimension for a
        # single-example forward pass
        no_unsqueeze = {"pixel_values", "image_grid_thw"}
        batch = {k: (v if k in no_unsqueeze else v.unsqueeze(0)).to(model.device)
                 for k, v in batch.items()}
        with torch.no_grad():
            out = model(**batch)
        print(f"loss on 1 example: {out.loss.item():.4f}")
        return

    trainer.train()
    model.save_pretrained(output_dir)
    print(f"LoRA adapter saved to {output_dir}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--dataset-dir", default=os.path.join(REPO, "checkpoints", "vision_distillation_dataset"))
    p.add_argument("--output-dir", default=os.path.join(REPO, "checkpoints", "qwen25vl_lora_vision"))
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--lora-r", type=int, default=16)
    p.add_argument("--lora-alpha", type=int, default=32)
    p.add_argument("--max-steps", type=int, default=None)
    p.add_argument("--dry-run", action="store_true",
                    help="build one batch and compute loss only, don't actually train -- "
                         "sanity-checks the data pipeline before committing to a real run")
    args = p.parse_args()
    train(args.dataset_dir, args.output_dir, args.epochs, args.lr,
          args.lora_r, args.lora_alpha, args.max_steps, args.dry_run)
